from MakeData import *


data = [['Classroom A', 0, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom B', 1, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom D', 2, 'Analogue Electronics', 'Freddie Seabrook \xa0'],
        ['Classroom A', 3, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom C', 4, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom B', 5, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom C', 6, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom D', 7, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom A', 8, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom B', 9, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom A', 10, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom B', 11, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom F', 12, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom B', 13, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom A', 14, 'Analogue Electronics', 'Lavenia Abdalla \xa0'],
        ['Classroom F', 15, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom A', 16, 'Analogue Electronics', 'Freddie Seabrook \xa0'],
        ['Classroom C', 17, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom A', 18, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom C', 19, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom E', 20, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom D', 21, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom A', 22, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom B', 23, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom C', 24, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom B', 25, 'Analogue Electronics', 'Freddie Seabrook \xa0'],
        ['Classroom C', 26, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom B', 27, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom A', 28, 'Analogue Electronics', 'Nam Mckeller \xa0'],
        ['Classroom B', 29, 'Analogue Electronics', 'Kristle Benshoof \xa0'],
        ['Classroom A', 0, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom B', 1, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom D', 2, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom A', 3, 'Communications Networks 1', 'Nancy Riess \xa0'],
        ['Classroom C', 4, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 5, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom C', 6, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom D', 7, 'Communications Networks 1', 'Paul Vandergrift \xa0'],
        ['Classroom A', 8, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 9, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom A', 10, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom B', 11, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom F', 12, 'Communications Networks 1', 'Irina Foose \xa0'],
        ['Classroom B', 13, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom A', 14, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom F', 15, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom A', 16, 'Communications Networks 1', 'Nancy Riess \xa0'],
        ['Classroom C', 17, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom A', 18, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom C', 19, 'Communications Networks 1', 'Paul Vandergrift \xa0'],
        ['Classroom E', 20, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom D', 21, 'Communications Networks 1', 'Nancy Riess \xa0'],
        ['Classroom A', 22, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 23, 'Communications Networks 1', 'Nancy Riess \xa0'],
        ['Classroom C', 24, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom B', 25, 'Communications Networks 1', 'Katherina Boutwell \xa0'],
        ['Classroom C', 26, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom B', 27, 'Communications Networks 1', 'Irina Foose \xa0'],
        ['Classroom A', 28, 'Communications Networks 1', 'Paul Vandergrift \xa0'],
        ['Classroom B', 29, 'Communications Networks 1', 'Freddie Seabrook \xa0'],
        ['Classroom A', 0, 'Computer Architecture 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 1, 'Computer Architecture 1', 'Lavenia Abdalla \xa0'],
        ['Classroom D', 2, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 3, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom C', 4, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom B', 5, 'Computer Architecture 1', 'Katherina Boutwell \xa0'],
        ['Classroom C', 6, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom D', 7, 'Computer Architecture 1', 'Kristle Benshoof \xa0'],
        ['Classroom A', 8, 'Computer Architecture 1', 'Lavenia Abdalla \xa0'],
        ['Classroom B', 9, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 10, 'Computer Architecture 1', 'Cathryn Bendel \xa0'],
        ['Classroom B', 11, 'Computer Architecture 1', 'Kristle Benshoof \xa0'],
        ['Classroom F', 12, 'Computer Architecture 1', 'Tyesha Gong \xa0'],
        ['Classroom B', 13, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 14, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom F', 15, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 16, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom C', 17, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 18, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom C', 19, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom E', 20, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom D', 21, 'Computer Architecture 1', 'Tyesha Gong \xa0'],
        ['Classroom A', 22, 'Computer Architecture 1', 'Tyesha Gong \xa0'],
        ['Classroom B', 23, 'Computer Architecture 1', 'Tyesha Gong \xa0'],
        ['Classroom C', 24, 'Computer Architecture 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 25, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom C', 26, 'Computer Architecture 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 27, 'Computer Architecture 1', 'Tyesha Gong \xa0'],
        ['Classroom A', 28, 'Computer Architecture 1', 'Kristle Benshoof \xa0'],
        ['Classroom B', 29, 'Computer Architecture 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 0, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom B', 1, 'Digital Electronic Design', 'Nisha Pal \xa0'],
        ['Classroom D', 2, 'Digital Electronic Design', 'Tyesha Gong \xa0'],
        ['Classroom A', 3, 'Digital Electronic Design', 'Kristle Benshoof \xa0'],
        ['Classroom C', 4, 'Digital Electronic Design', 'Paul Vandergrift \xa0'],
        ['Classroom B', 5, 'Digital Electronic Design', 'Paul Vandergrift \xa0'],
        ['Classroom C', 6, 'Digital Electronic Design', 'Kristle Benshoof \xa0'],
        ['Classroom D', 7, 'Digital Electronic Design', 'Tyesha Gong \xa0'],
        ['Classroom A', 8, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom B', 9, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom A', 10, 'Digital Electronic Design', 'Ian Hooper \xa0'],
        ['Classroom B', 11, 'Digital Electronic Design', 'Cathryn Bendel \xa0'],
        ['Classroom F', 12, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom B', 13, 'Digital Electronic Design', 'Kristle Benshoof \xa0'],
        ['Classroom A', 14, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom F', 15, 'Digital Electronic Design', 'Kristle Benshoof \xa0'],
        ['Classroom A', 16, 'Digital Electronic Design', 'Cathryn Bendel \xa0'],
        ['Classroom C', 17, 'Digital Electronic Design', 'Cathryn Bendel \xa0'],
        ['Classroom A', 18, 'Digital Electronic Design', 'Nisha Pal \xa0'],
        ['Classroom C', 19, 'Digital Electronic Design', 'Kristle Benshoof \xa0'],
        ['Classroom E', 20, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom D', 21, 'Digital Electronic Design', 'Nisha Pal \xa0'],
        ['Classroom A', 22, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom B', 23, 'Digital Electronic Design', 'Paul Vandergrift \xa0'],
        ['Classroom C', 24, 'Digital Electronic Design', 'Tyesha Gong \xa0'],
        ['Classroom B', 25, 'Digital Electronic Design', 'Nancy Riess \xa0'],
        ['Classroom C', 26, 'Digital Electronic Design', 'Tyesha Gong \xa0'],
        ['Classroom B', 27, 'Digital Electronic Design', 'Cathryn Bendel \xa0'],
        ['Classroom A', 28, 'Digital Electronic Design', 'Tyesha Gong \xa0'],
        ['Classroom B', 29, 'Digital Electronic Design', 'Ian Hooper \xa0'],
        ['Classroom A', 0, 'Electrical Systems', 'Tyesha Gong \xa0'],
        ['Classroom B', 1, 'Electrical Systems', 'Kylee Giblin \xa0'],
        ['Classroom D', 2, 'Electrical Systems', 'Lavenia Abdalla \xa0'],
        ['Classroom A', 3, 'Electrical Systems', 'Tyesha Gong \xa0'],
        ['Classroom C', 4, 'Electrical Systems', 'Tiffani Iannotti \xa0'],
        ['Classroom B', 5, 'Electrical Systems', 'Lavenia Abdalla \xa0'],
        ['Classroom C', 6, 'Electrical Systems', 'Cathryn Bendel \xa0'],
        ['Classroom A', 8, 'Electrical Systems', 'Nisha Pal \xa0'],
        ['Classroom B', 9, 'Electrical Systems', 'Tyesha Gong \xa0'],
        ['Classroom A', 10, 'Electrical Systems', 'Lavenia Abdalla \xa0'],
        ['Classroom B', 11, 'Electrical Systems', 'Tiffani Iannotti \xa0'],
        ['Classroom F', 12, 'Electrical Systems', 'Cathryn Bendel \xa0'],
        ['Classroom B', 13, 'Electrical Systems', 'Paul Vandergrift \xa0'],
        ['Classroom A', 14, 'Electrical Systems', 'Cathryn Bendel \xa0'],
        ['Classroom F', 15, 'Electrical Systems', 'Cathryn Bendel \xa0'],
        ['Classroom A', 16, 'Electrical Systems', 'Paul Vandergrift \xa0'],
        ['Classroom C', 17, 'Electrical Systems', 'Paul Vandergrift \xa0'],
        ['Classroom A', 18, 'Electrical Systems', 'Tiffani Iannotti \xa0'],
        ['Classroom C', 19, 'Electrical Systems', 'Tyesha Gong \xa0'],
        ['Classroom E', 20, 'Electrical Systems', 'Tyesha Gong \xa0'],
        ['Classroom D', 21, 'Electrical Systems', 'Eliza Biddle \xa0'],
        ['Classroom A', 22, 'Electrical Systems', 'Lavenia Abdalla \xa0'],
        ['Classroom B', 23, 'Electrical Systems', 'Nisha Pal \xa0'],
        ['Classroom C', 24, 'Electrical Systems', 'Cathryn Bendel \xa0'],
        ['Classroom B', 25, 'Electrical Systems', 'Tyesha Gong \xa0'],
        ['Classroom C', 26, 'Electrical Systems', 'Paul Vandergrift \xa0'],
        ['Classroom B', 27, 'Electrical Systems', 'Paul Vandergrift \xa0'],
        ['Classroom A', 28, 'Electrical Systems', 'Cathryn Bendel \xa0'],
        ['Classroom B', 29, 'Electrical Systems', 'Kylee Giblin \xa0'],
        ['Classroom D', 30, 'Electrical Systems', 'Melina Aldinger \xa0'],
        ['Classroom A', 0, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom B', 1, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom D', 2, 'Intro to Elec Energy Systems 1', 'Eliza Biddle \xa0'],
        ['Classroom A', 3, 'Intro to Elec Energy Systems 1', 'Nisha Pal \xa0'],
        ['Classroom C', 4, 'Intro to Elec Energy Systems 1', 'Ruth Frew \xa0'],
        ['Classroom B', 5, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom C', 6, 'Intro to Elec Energy Systems 1', 'Lavenia Abdalla \xa0'],
        ['Classroom A', 8, 'Intro to Elec Energy Systems 1', 'Eliza Biddle \xa0'],
        ['Classroom B', 9, 'Intro to Elec Energy Systems 1', 'Lavenia Abdalla \xa0'],
        ['Classroom A', 10, 'Intro to Elec Energy Systems 1', 'Eliza Biddle \xa0'],
        ['Classroom B', 11, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom B', 13, 'Intro to Elec Energy Systems 1', 'Nancy Riess \xa0'],
        ['Classroom A', 14, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom F', 15, 'Intro to Elec Energy Systems 1', 'Katherina Boutwell \xa0'],
        ['Classroom A', 16, 'Intro to Elec Energy Systems 1', 'Nisha Pal \xa0'],
        ['Classroom C', 17, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom A', 18, 'Intro to Elec Energy Systems 1', 'Ruth Frew \xa0'],
        ['Classroom C', 19, 'Intro to Elec Energy Systems 1', 'Lavenia Abdalla \xa0'],
        ['Classroom E', 20, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom A', 22, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom B', 23, 'Intro to Elec Energy Systems 1', 'Lavenia Abdalla \xa0'],
        ['Classroom C', 24, 'Intro to Elec Energy Systems 1', 'Lavenia Abdalla \xa0'],
        ['Classroom B', 25, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom C', 26, 'Intro to Elec Energy Systems 1', 'Irina Foose \xa0'],
        ['Classroom B', 27, 'Intro to Elec Energy Systems 1', 'Nisha Pal \xa0'],
        ['Classroom A', 28, 'Intro to Elec Energy Systems 1', 'Ruth Frew \xa0'],
        ['Classroom B', 29, 'Intro to Elec Energy Systems 1', 'Eliza Biddle \xa0'],
        ['Classroom D', 30, 'Intro to Elec Energy Systems 1', 'Katherina Boutwell \xa0'],
        ['Classroom B', 31, 'Intro to Elec Energy Systems 1', 'Kristle Benshoof \xa0'],
        ['Classroom A', 32, 'Intro to Elec Energy Systems 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 0, 'Introduction to Control', 'Tiffani Iannotti \xa0'],
        ['Classroom D', 2, 'Introduction to Control', 'Ruth Frew \xa0'],
        ['Classroom A', 3, 'Introduction to Control', 'Cathryn Bendel \xa0'],
        ['Classroom C', 4, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom B', 5, 'Introduction to Control', 'Tiffani Iannotti \xa0'],
        ['Classroom C', 6, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom D', 7, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom A', 8, 'Introduction to Control', 'Tiffani Iannotti \xa0'],
        ['Classroom B', 9, 'Introduction to Control', 'Cathryn Bendel \xa0'],
        ['Classroom A', 10, 'Introduction to Control', 'Tiffani Iannotti \xa0'],
        ['Classroom B', 11, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom F', 12, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom B', 13, 'Introduction to Control', 'Tiffani Iannotti \xa0'],
        ['Classroom A', 14, 'Introduction to Control', 'Ruth Frew \xa0'],
        ['Classroom F', 15, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom A', 16, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom C', 17, 'Introduction to Control', 'Eliza Biddle \xa0'],
        ['Classroom A', 18, 'Introduction to Control', 'Waltraud Fill \xa0'],
        ['Classroom C', 19, 'Introduction to Control', 'Cathryn Bendel \xa0'],
        ['Classroom E', 20, 'Introduction to Control', 'Lavenia Abdalla \xa0'],
        ['Classroom D', 21, 'Introduction to Control', 'Waltraud Fill \xa0'],
        ['Classroom A', 22, 'Introduction to Control', 'Tiffani Iannotti \xa0'],
        ['Classroom B', 23, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom C', 24, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom B', 25, 'Introduction to Control', 'Cathryn Bendel \xa0'],
        ['Classroom C', 26, 'Introduction to Control', 'Lavenia Abdalla \xa0'],
        ['Classroom B', 27, 'Introduction to Control', 'Lavenia Abdalla \xa0'],
        ['Classroom A', 28, 'Introduction to Control', 'Ian Hooper \xa0'],
        ['Classroom B', 29, 'Introduction to Control', 'Ruth Frew \xa0'],
        ['Classroom D', 30, 'Introduction to Control', 'Tyesha Gong \xa0'],
        ['Classroom A', 0, 'Mathematics 2', 'Ruth Frew \xa0'], ['Classroom A', 3, 'Mathematics 2', 'Ian Hooper \xa0'],
        ['Classroom B', 5, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom C', 6, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom A', 8, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom B', 9, 'Mathematics 2', 'Ian Hooper \xa0'],
        ['Classroom B', 11, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom F', 12, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom B', 13, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom F', 15, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom A', 16, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom C', 17, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom C', 19, 'Mathematics 2', 'Ian Hooper \xa0'],
        ['Classroom E', 20, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom A', 22, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom B', 23, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom C', 24, 'Mathematics 2', 'Eliza Biddle \xa0'],
        ['Classroom B', 25, 'Mathematics 2', 'Ian Hooper \xa0'],
        ['Classroom C', 26, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom B', 27, 'Mathematics 2', 'Eliza Biddle \xa0'],
        ['Classroom A', 28, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom D', 30, 'Mathematics 2', 'Cathryn Bendel \xa0'],
        ['Classroom B', 31, 'Mathematics 2', 'Tyesha Gong \xa0'],
        ['Classroom A', 32, 'Mathematics 2', 'Katherina Boutwell \xa0'],
        ['Classroom E', 33, 'Mathematics 2', 'Katherina Boutwell \xa0'],
        ['Classroom F', 34, 'Mathematics 2', 'Katherina Boutwell \xa0'],
        ['Classroom B', 35, 'Mathematics 2', 'Katherina Boutwell \xa0'],
        ['Classroom A', 36, 'Mathematics 2', 'Kylee Giblin \xa0'],
        ['Classroom B', 37, 'Mathematics 2', 'Tyesha Gong \xa0'],
        ['Classroom A', 38, 'Mathematics 2', 'Nam Mckeller \xa0'],
        ['Classroom A', 0, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom A', 3, 'Mathematics 3', 'Lavenia Abdalla \xa0'],
        ['Classroom C', 4, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom B', 5, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom C', 6, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom A', 8, 'Mathematics 3', 'Ruth Frew \xa0'],
        ['Classroom B', 9, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom B', 11, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom F', 12, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom B', 13, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom F', 15, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom A', 16, 'Mathematics 3', 'Tiffani Iannotti \xa0'],
        ['Classroom C', 19, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom E', 20, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom A', 22, 'Mathematics 3', 'Ruth Frew \xa0'],
        ['Classroom B', 23, 'Mathematics 3', 'Tiffani Iannotti \xa0'],
        ['Classroom C', 24, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom B', 25, 'Mathematics 3', 'Paul Vandergrift \xa0'],
        ['Classroom C', 26, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom B', 27, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom A', 28, 'Mathematics 3', 'Waltraud Fill \xa0'],
        ['Classroom D', 30, 'Mathematics 3', 'Ruth Frew \xa0'],
        ['Classroom B', 31, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom A', 32, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom E', 33, 'Mathematics 3', 'Tiffani Iannotti \xa0'],
        ['Classroom F', 34, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom B', 35, 'Mathematics 3', 'Tyesha Gong \xa0'],
        ['Classroom A', 36, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom B', 37, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom A', 38, 'Mathematics 3', 'Irina Foose \xa0'],
        ['Classroom B', 1, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom A', 3, 'Programming 1', 'Tiffani Iannotti \xa0'],
        ['Classroom B', 5, 'Programming 1', 'Ruth Frew \xa0'],
        ['Classroom C', 6, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom D', 7, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom A', 8, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom B', 9, 'Programming 1', 'Tiffani Iannotti \xa0'],
        ['Classroom A', 10, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom B', 13, 'Programming 1', 'Ruth Frew \xa0'],
        ['Classroom A', 14, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom F', 15, 'Programming 1', 'Tiffani Iannotti \xa0'],
        ['Classroom C', 19, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom E', 20, 'Programming 1', 'Tiffani Iannotti \xa0'],
        ['Classroom A', 22, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom B', 23, 'Programming 1', 'Ruth Frew \xa0'],
        ['Classroom C', 24, 'Programming 1', 'Tiffani Iannotti \xa0'],
        ['Classroom B', 25, 'Programming 1', 'Lavenia Abdalla \xa0'],
        ['Classroom C', 26, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom B', 27, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom A', 28, 'Programming 1', 'Hobert Pascarella \xa0'],
        ['Classroom B', 31, 'Programming 1', 'Tiffani Iannotti \xa0'],
        ['Classroom A', 32, 'Programming 1', 'Cathryn Bendel \xa0'],
        ['Classroom E', 33, 'Programming 1', 'Kristle Benshoof \xa0'],
        ['Classroom F', 34, 'Programming 1', 'Kristle Benshoof \xa0'],
        ['Classroom B', 35, 'Programming 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 36, 'Programming 1', 'Melina Aldinger \xa0'],
        ['Classroom B', 37, 'Programming 1', 'Kristle Benshoof \xa0'],
        ['Classroom A', 38, 'Programming 1', 'Kristle Benshoof \xa0'],
        ['Classroom B', 39, 'Programming 1', 'Melina Aldinger \xa0'],
        ['Classroom C', 40, 'Programming 1', 'Melina Aldinger \xa0'],
        ['Classroom A', 0, 'Signals and Systems', 'Nisha Pal \xa0'],
        ['Classroom D', 2, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom A', 3, 'Signals and Systems', 'Kylee Giblin \xa0'],
        ['Classroom C', 4, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom B', 5, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom C', 6, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom A', 8, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom B', 9, 'Signals and Systems', 'Kylee Giblin \xa0'],
        ['Classroom A', 10, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom F', 12, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom A', 14, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom F', 15, 'Signals and Systems', 'Nancy Riess \xa0'],
        ['Classroom C', 17, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom A', 18, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom E', 20, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom C', 24, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom B', 25, 'Signals and Systems', 'Nisha Pal \xa0'],
        ['Classroom C', 26, 'Signals and Systems', 'Nisha Pal \xa0'],
        ['Classroom B', 27, 'Signals and Systems', 'Ruth Frew \xa0'],
        ['Classroom B', 29, 'Signals and Systems', 'Joi Shriver \xa0'],
        ['Classroom B', 31, 'Signals and Systems', 'Freddie Seabrook \xa0'],
        ['Classroom A', 32, 'Signals and Systems', 'Tiffani Iannotti \xa0'],
        ['Classroom E', 33, 'Signals and Systems', 'Freddie Seabrook \xa0'],
        ['Classroom F', 34, 'Signals and Systems', 'Nancy Riess \xa0'],
        ['Classroom B', 35, 'Signals and Systems', 'Freddie Seabrook \xa0'],
        ['Classroom A', 36, 'Signals and Systems', 'Nancy Riess \xa0'],
        ['Classroom B', 37, 'Signals and Systems', 'Freddie Seabrook \xa0'],
        ['Classroom A', 38, 'Signals and Systems', 'Freddie Seabrook \xa0'],
        ['Classroom B', 39, 'Signals and Systems', 'Nancy Riess \xa0'],
        ['Classroom C', 40, 'Signals and Systems', 'Freddie Seabrook \xa0'],
        ['Classroom A', 3, 'Software Development', 'Hobert Pascarella \xa0'],
        ['Classroom F', 15, 'Software Development', 'Ruth Frew \xa0'],
        ['Classroom E', 20, 'Software Development', 'Hobert Pascarella \xa0'],
        ['Classroom C', 24, 'Software Development', 'Ruth Frew \xa0'],
        ['Classroom B', 25, 'Software Development', 'Tiffani Iannotti \xa0'],
        ['Classroom C', 26, 'Software Development', 'Joi Shriver \xa0'],
        ['Classroom B', 31, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom A', 32, 'Software Development', 'Hobert Pascarella \xa0'],
        ['Classroom E', 33, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom F', 34, 'Software Development', 'Tyesha Gong \xa0'],
        ['Classroom B', 35, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom A', 36, 'Software Development', 'Hobert Pascarella \xa0'],
        ['Classroom B', 37, 'Software Development', 'Tiffani Iannotti \xa0'],
        ['Classroom A', 38, 'Software Development', 'Tyesha Gong \xa0'],
        ['Classroom B', 39, 'Software Development', 'Nam Mckeller \xa0'],
        ['Classroom C', 40, 'Software Development', 'Nam Mckeller \xa0'],
        ['Classroom A', 41, 'Software Development', 'Nisha Pal \xa0'],
        ['Classroom D', 42, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom B', 43, 'Software Development', 'Nam Mckeller \xa0'],
        ['Classroom C', 44, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom A', 45, 'Software Development', 'Tyesha Gong \xa0'],
        ['Classroom B', 46, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom D', 47, 'Software Development', 'Nam Mckeller \xa0'],
        ['Classroom C', 48, 'Software Development', 'Nam Mckeller \xa0'],
        ['Classroom B', 49, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom C', 50, 'Software Development', 'Nam Mckeller \xa0'],
        ['Classroom B', 51, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom A', 52, 'Software Development', 'Nancy Riess \xa0'],
        ['Classroom B', 53, 'Software Development', 'Tyesha Gong \xa0'],
        ['Classroom C', 54, 'Software Development', 'Nancy Riess \xa0']]



