import random
import numpy as np

timetable = [[2, 'Classroom K', 'Freddie Seabrook \xa0', 'Subject 2', 'Lecture'],
             [4, 'Classroom E', 'Jane Courtney ', 'Subject 26', 'Lecture'],
             [28, 'Classroom J', 'Paul Vandergrift \xa0', 'Subject 15', 'Lecture'],
             [18, 'Classroom K', 'Jane Courtney ', 'Subject 26', 'Lecture'],
             [40, 'Classroom H', 'Lavenia Abdalla \xa0', 'Subject 17', 'Lecture'],
             [30, 'Classroom I', 'Ruth Frew \xa0', 'Subject 5', 'Lecture'],
             [56, 'Classroom I', 'Hobert Pascarella \xa0', 'Subject 5', 'Lecture'],
             [28, 'Classroom K', 'Katherina Boutwell \xa0', 'Subject 16', 'Lecture'],
             [33, 'Classroom A', 'Ruth Frew \xa0', 'Subject 32', 'Lecture'],
             [36, 'Classroom K', 'Waltraud Fill \xa0', 'Subject 3', 'Lecture'],
             [54, 'Classroom G', 'Kylee Giblin \xa0', 'Subject 19', 'Lecture'],
             [39, 'Classroom H', 'Nisha Pal \xa0', 'Subject 16', 'Lecture'],
             [17, 'Classroom H', 'Jane Courtney ', 'Subject 19', 'Lecture'],
             [13, 'Classroom H', 'Ian Hooper \xa0', 'Subject 29', 'Lecture'],
             [19, 'Classroom E', 'Jane Courtney ', 'Subject 25', 'Lecture'],
             [23, 'Classroom J', 'Ian Hooper \xa0', 'Subject 34', 'Lecture'],
             [47, 'Classroom K', 'Ruth Frew \xa0', 'Subject 14', 'Lecture'],
             [26, 'Classroom I', 'Freddie Seabrook \xa0', 'Subject 2', 'Lecture'],
             [47, 'Classroom A', 'Tyesha Gong \xa0', 'Subject 32', 'Lecture'],
             [11, 'Classroom J', 'Lavenia Abdalla \xa0', 'Subject 7', 'Lecture'],
             [32, 'Classroom H', 'Eliza Biddle \xa0', 'Subject 4', 'Lecture'],
             [31, 'Classroom H', 'Kristle Benshoof \xa0', 'Subject 31', 'Lecture'],
             [46, 'Classroom B', 'Joi Shriver \xa0', 'Subject 6', 'Lecture'],
             [63, 'Classroom D', 'Kylee Giblin \xa0', 'Subject 27', 'Lecture'],
             [10, 'Classroom E', 'Kylee Giblin \xa0', 'Subject 8', 'Lecture'],
             [9, 'Classroom I', 'Kristle Benshoof \xa0', 'Subject 28', 'Lecture'],
             [55, 'Classroom A', 'Ruth Frew \xa0', 'Subject 12', 'Lecture'],
             [50, 'Classroom K', 'Cathryn Bendel \xa0', 'Subject 23', 'Lecture'],
             [39, 'Classroom D', 'Cathryn Bendel \xa0', 'Subject 28', 'Lecture'],
             [2, 'Classroom J', 'Katherina Boutwell \xa0', 'Subject 3', 'Lecture'],
             [29, 'Lab B', 'Nancy Riess \xa0', 'Subject 13-Lab', 'Lab'],
             [48, 'Classroom E', 'Ian Hooper \xa0', 'Subject 12', 'Lecture'],
             [5, 'Classroom H', 'Nisha Pal \xa0', 'Subject 15', 'Lecture'],
             [16, 'Classroom G', 'Hobert Pascarella \xa0', 'Subject 25', 'Lecture'],
             [50, 'Classroom G', 'Cathryn Bendel \xa0', 'Subject 13', 'Lecture'],
             [29, 'Classroom E', 'Ian Hooper \xa0', 'Subject 17', 'Lecture'],
             [56, 'Classroom K', 'Nam Mckeller \xa0', 'Subject 4', 'Lecture'],
             [5, 'Classroom H', 'Cathryn Bendel \xa0', 'Subject 23', 'Lecture'],
             [36, 'Classroom J', 'Tiffani Iannotti \xa0', 'Subject 3', 'Lecture'],
             [53, 'Classroom G', 'Ian Hooper \xa0', 'Subject 23', 'Lecture'],
             [30, 'Classroom J', 'Kylee Giblin \xa0', 'Subject 27', 'Lecture'],
             [26, 'Classroom E', 'Ian Hooper \xa0', 'Subject 34', 'Lecture'],
             [55, 'Classroom K', 'Freddie Seabrook \xa0', 'Subject 1', 'Lecture'],
             [10, 'Classroom F', 'Paul Vandergrift \xa0', 'Subject 31', 'Lecture'],
             [7, 'Classroom A', 'Irina Foose \xa0', 'Subject 30', 'Lecture'],
             [41, 'Lab D', 'Freddie Seabrook \xa0', 'Subject 4-Lab', 'Lab'],
             [14, 'Classroom C', 'Cathryn Bendel \xa0', 'Subject 29', 'Lecture'],
             [11, 'Classroom J', 'Jane Courtney ', 'Subject 22', 'Lecture'],
             [1, 'Classroom E', 'Tiffani Iannotti \xa0', 'Subject 11', 'Lecture'],
             [52, 'Classroom C', 'Cathryn Bendel \xa0', 'Subject 33', 'Lecture'],
             [50, 'Classroom A', 'Kylee Giblin \xa0', 'Subject 27', 'Lecture'],
             [22, 'Classroom I', 'Lavenia Abdalla \xa0', 'Subject 22', 'Lecture'],
             [49, 'Classroom I', 'Paul Vandergrift \xa0', 'Subject 17', 'Lecture'],
             [40, 'Classroom A', 'Nisha Pal \xa0', 'Subject 16', 'Lecture'],
             [63, 'Classroom J', 'Kristle Benshoof \xa0', 'Subject 8', 'Lecture'],
             [30, 'Lab A', 'Hobert Pascarella \xa0', 'Subject 15-Lab', 'Lab'],
             [39, 'Classroom K', 'Kristle Benshoof \xa0', 'Subject 9', 'Lecture'],
             [36, 'Classroom G', 'Paul Vandergrift \xa0', 'Subject 20', 'Lecture'],
             [31, 'Classroom J', 'Tyesha Gong \xa0', 'Subject 3', 'Lecture'],
             [14, 'Classroom A', 'Tyesha Gong \xa0', 'Subject 6', 'Lecture'],
             [1, 'Classroom I', 'Nisha Pal \xa0', 'Subject 29', 'Lecture'],
             [19, 'Classroom B', 'Nam Mckeller \xa0', 'Subject 4', 'Lecture'],
             [38, 'Classroom J', 'Nisha Pal \xa0', 'Subject 29', 'Lecture'],
             [8, 'Classroom C', 'Jane Courtney ', 'Subject 21', 'Lecture'],
             [61, 'Classroom B', 'Joi Shriver \xa0', 'Subject 32', 'Lecture'],
             [30, 'Classroom J', 'Nam Mckeller \xa0', 'Subject 12', 'Lecture'],
             [53, 'Lab F', 'Tyesha Gong \xa0', 'Subject 1-Lab', 'Lab'],
             [11, 'Classroom C', 'Tiffani Iannotti \xa0', 'Subject 16', 'Lecture'],
             [50, 'Classroom I', 'Tyesha Gong \xa0', 'Subject 31', 'Lecture'],
             [52, 'Classroom A', 'Freddie Seabrook \xa0', 'Subject 1', 'Lecture'],
             [23, 'Classroom A', 'Hobert Pascarella \xa0', 'Subject 15', 'Lecture'],
             [9, 'Classroom E', 'Nisha Pal \xa0', 'Subject 30', 'Lecture'],
             [49, 'Classroom F', 'Ruth Frew \xa0', 'Subject 24', 'Lecture'],
             [41, 'Time', 'Nam Mckeller \xa0', 'Subject 12-Lab', 'Lab'],
             [43, 'Classroom B', 'Tiffani Iannotti \xa0', 'Subject 14', 'Lecture'],
             [5, 'Lab A', 'Waltraud Fill \xa0', 'Subject 23-Lab', 'Lab'],
             [57, 'Classroom C', 'Lavenia Abdalla \xa0', 'Subject 32', 'Lecture'],
             [50, 'Classroom C', 'Kylee Giblin \xa0', 'Subject 14', 'Lecture'],
             [13, 'Classroom A', 'Hobert Pascarella \xa0', 'Subject 26', 'Lecture'],
             [40, 'Classroom C', 'Nam Mckeller \xa0', 'Subject 25', 'Lecture'],
             [8, 'Classroom G', 'Freddie Seabrook \xa0', 'Subject 1', 'Lecture'],
             [0, 'Classroom H', 'Kylee Giblin \xa0', 'Subject 34', 'Lecture'],
             [53, 'Classroom E', 'Katherina Boutwell \xa0', 'Subject 10', 'Lecture'],
             [49, 'Time', 'Paul Vandergrift \xa0', 'Subject 6-Lab', 'Lab'],
             [7, 'Classroom I', 'Tiffani Iannotti \xa0', 'Subject 3', 'Lecture'],
             [60, 'Classroom F', 'Tiffani Iannotti \xa0', 'Subject 24', 'Lecture'],
             [54, 'Classroom K', 'Tiffani Iannotti \xa0', 'Subject 5', 'Lecture'],
             [42, 'Classroom A', 'Nancy Riess \xa0', 'Subject 33', 'Lecture'],
             [44, 'Classroom H', 'Tiffani Iannotti \xa0', 'Subject 25', 'Lecture'],
             [32, 'Classroom H', 'Paul Vandergrift \xa0', 'Subject 27', 'Lecture'],
             [1, 'Classroom B', 'Kristle Benshoof \xa0', 'Subject 11', 'Lecture'],
             [44, 'Classroom D', 'Cathryn Bendel \xa0', 'Subject 20', 'Lecture'],
             [14, 'Classroom B', 'Ian Hooper \xa0', 'Subject 4', 'Lecture'],
             [42, 'Classroom E', 'Lavenia Abdalla \xa0', 'Subject 12', 'Lecture'],
             [43, 'Classroom D', 'Cathryn Bendel \xa0', 'Subject 17', 'Lecture'],
             [36, 'Classroom D', 'Ian Hooper \xa0', 'Subject 26', 'Lecture'],
             [26, 'Classroom G', 'Kylee Giblin \xa0', 'Subject 8', 'Lecture'],
             [20, 'Classroom I', 'Eliza Biddle \xa0', 'Subject 7', 'Lecture'],
             [28, 'Classroom D', 'Hobert Pascarella \xa0', 'Subject 8', 'Lecture'],
             [18, 'Classroom H', 'Katherina Boutwell \xa0', 'Subject 33', 'Lecture'],
             [30, 'Classroom H', 'Jane Courtney ', 'Subject 16', 'Lecture'],
             [51, 'Classroom C', 'Ian Hooper \xa0', 'Subject 17', 'Lecture'],
             [16, 'Classroom D', 'Katherina Boutwell \xa0', 'Subject 14', 'Lecture'],
             [33, 'Classroom F', 'Tyesha Gong \xa0', 'Subject 32', 'Lecture'],
             [24, 'Classroom B', 'Waltraud Fill \xa0', 'Subject 11', 'Lecture'],
             [41, 'Classroom K', 'Ruth Frew \xa0', 'Subject 34', 'Lecture'],
             [21, 'Classroom B', 'Lavenia Abdalla \xa0', 'Subject 29', 'Lecture'],
             [36, 'Classroom I', 'Hobert Pascarella \xa0', 'Subject 9', 'Lecture'],
             [20, 'Classroom D', 'Nisha Pal \xa0', 'Subject 28', 'Lecture'],
             [20, 'Classroom C', 'Eliza Biddle \xa0', 'Subject 3', 'Lecture'],
             [26, 'Classroom F', 'Freddie Seabrook \xa0', 'Subject 2', 'Lecture'],
             [46, 'Classroom D', 'Ruth Frew \xa0', 'Subject 21', 'Lecture'],
             [43, 'Classroom G', 'Joi Shriver \xa0', 'Subject 21', 'Lecture'],
             [29, 'Classroom B', 'Kylee Giblin \xa0', 'Subject 18', 'Lecture'],
             [37, 'Classroom D', 'Katherina Boutwell \xa0', 'Subject 33', 'Lecture'],
             [47, 'Classroom H', 'Lavenia Abdalla \xa0', 'Subject 1', 'Lecture'],
             [3, 'Classroom G', 'Katherina Boutwell \xa0', 'Subject 13', 'Lecture'],
             [59, 'Classroom F', 'Lavenia Abdalla \xa0', 'Subject 22', 'Lecture'],
             [34, 'Classroom F', 'Hobert Pascarella \xa0', 'Subject 2', 'Lecture'],
             [21, 'Classroom K', 'Waltraud Fill \xa0', 'Subject 22', 'Lecture'],
             [44, 'Classroom K', 'Ruth Frew \xa0', 'Subject 11', 'Lecture'],
             [38, 'Classroom H', 'Joi Shriver \xa0', 'Subject 24', 'Lecture'],
             [58, 'Classroom F', 'Hobert Pascarella \xa0', 'Subject 32', 'Lecture'],
             [37, 'Classroom K', 'Katherina Boutwell \xa0', 'Subject 20', 'Lecture'],
             [4, 'Classroom F', 'Ruth Frew \xa0', 'Subject 30', 'Lecture'],
             [63, 'Classroom A', 'Tiffani Iannotti \xa0', 'Subject 11', 'Lecture'],
             [37, 'Classroom H', 'Eliza Biddle \xa0', 'Subject 6', 'Lecture'],
             [2, 'Classroom D', 'Hobert Pascarella \xa0', 'Subject 16', 'Lecture'],
             [1, 'Classroom D', 'Nam Mckeller \xa0', 'Subject 7', 'Lecture'],
             [22, 'Classroom K', 'Ian Hooper \xa0', 'Subject 30', 'Lecture'],
             [9, 'Classroom H', 'Nancy Riess \xa0', 'Subject 24', 'Lecture'],
             [6, 'Classroom K', 'Freddie Seabrook \xa0', 'Subject 34', 'Lecture'],
             [26, 'Classroom A', 'Nisha Pal \xa0', 'Subject 9', 'Lecture'],
             [12, 'Classroom F', 'Tyesha Gong \xa0', 'Subject 4', 'Lecture'],
             [23, 'Classroom C', 'Tiffani Iannotti \xa0', 'Subject 1', 'Lecture'],
             [42, 'Classroom C', 'Jane Courtney ', 'Subject 30', 'Lecture'],
             [52, 'Classroom A', 'Jane Courtney ', 'Subject 1', 'Lecture'],
             [57, 'Classroom A', 'Tyesha Gong \xa0', 'Subject 33', 'Lecture'],
             [31, 'Classroom G', 'Nam Mckeller \xa0', 'Subject 7', 'Lecture'],
             [21, 'Classroom J', 'Eliza Biddle \xa0', 'Subject 4', 'Lecture'],
             [61, 'Classroom J', 'Paul Vandergrift \xa0', 'Subject 21', 'Lecture'],
             [40, 'Classroom B', 'Katherina Boutwell \xa0', 'Subject 5', 'Lecture'],
             [35, 'Classroom I', 'Kristle Benshoof \xa0', 'Subject 5', 'Lecture'],
             [34, 'Classroom F', 'Nisha Pal \xa0', 'Subject 12', 'Lecture'],
             [2, 'Classroom C', 'Hobert Pascarella \xa0', 'Subject 7', 'Lecture'],
             [28, 'Classroom A', 'Tyesha Gong \xa0', 'Subject 27', 'Lecture'],
             [35, 'Classroom C', 'Ian Hooper \xa0', 'Subject 29', 'Lecture'],
             [35, 'Classroom G', 'Nam Mckeller \xa0', 'Subject 12', 'Lecture'],
             [39, 'Classroom E', 'Waltraud Fill \xa0', 'Subject 22', 'Lecture'],
             [48, 'Classroom A', 'Ian Hooper \xa0', 'Subject 8', 'Lecture'],
             [62, 'Classroom K', 'Joi Shriver \xa0', 'Subject 8', 'Lecture'],
             [39, 'Classroom F', 'Ruth Frew \xa0', 'Subject 31', 'Lecture'],
             [15, 'Classroom I', 'Tiffani Iannotti \xa0', 'Subject 11', 'Lecture'],
             [26, 'Classroom F', 'Kylee Giblin \xa0', 'Subject 18', 'Lecture'],
             [32, 'Classroom D', 'Paul Vandergrift \xa0', 'Subject 10', 'Lecture'],
             [39, 'Classroom K', 'Nisha Pal \xa0', 'Subject 22', 'Lecture'],
             [59, 'Classroom I', 'Kristle Benshoof \xa0', 'Subject 18', 'Lecture'],
             [10, 'Classroom H', 'Ruth Frew \xa0', 'Subject 34', 'Lecture'],
             [24, 'Classroom K', 'Waltraud Fill \xa0', 'Subject 13', 'Lecture'],
             [24, 'Classroom F', 'Nancy Riess \xa0', 'Subject 18', 'Lecture'],
             [26, 'Lab E', 'Waltraud Fill \xa0', 'Subject 8-Lab', 'Lab'],
             [6, 'Classroom B', 'Eliza Biddle \xa0', 'Subject 3', 'Lecture'],
             [38, 'Classroom C', 'Joi Shriver \xa0', 'Subject 28', 'Lecture'],
             [27, 'Classroom F', 'Cathryn Bendel \xa0', 'Subject 14', 'Lecture'],
             [23, 'Classroom J', 'Jane Courtney ', 'Subject 17', 'Lecture'],
             [3, 'Classroom C', 'Paul Vandergrift \xa0', 'Subject 6', 'Lecture'],
             [8, 'Classroom E', 'Jane Courtney ', 'Subject 28', 'Lecture'],
             [43, 'Classroom C', 'Eliza Biddle \xa0', 'Subject 21', 'Lecture'],
             [48, 'Classroom I', 'Paul Vandergrift \xa0', 'Subject 31', 'Lecture'],
             [61, 'Classroom H', 'Nisha Pal \xa0', 'Subject 9', 'Lecture'],
             [14, 'Time', 'Kristle Benshoof \xa0', 'Subject 30-Lab', 'Lab'],
             [5, 'Classroom E', 'Joi Shriver \xa0', 'Subject 20', 'Lecture'],
             [5, 'Classroom B', 'Freddie Seabrook \xa0', 'Subject 27', 'Lecture'],
             [40, 'Classroom J', 'Irina Foose \xa0', 'Subject 9', 'Lecture'],
             [10, 'Classroom J', 'Hobert Pascarella \xa0', 'Subject 7', 'Lecture'],
             [48, 'Classroom C', 'Ian Hooper \xa0', 'Subject 4', 'Lecture'],
             [52, 'Classroom G', 'Irina Foose \xa0', 'Subject 30', 'Lecture'],
             [1, 'Classroom H', 'Nam Mckeller \xa0', 'Subject 20', 'Lecture'],
             [25, 'Classroom C', 'Joi Shriver \xa0', 'Subject 28', 'Lecture'],
             [7, 'Classroom I', 'Tyesha Gong \xa0', 'Subject 6', 'Lecture'],
             [42, 'Classroom A', 'Eliza Biddle \xa0', 'Subject 19', 'Lecture'],
             [56, 'Classroom I', 'Lavenia Abdalla \xa0', 'Subject 26', 'Lecture'],
             [49, 'Classroom H', 'Nancy Riess \xa0', 'Subject 18', 'Lecture'],
             [32, 'Classroom E', 'Waltraud Fill \xa0', 'Subject 8', 'Lecture'],
             [58, 'Classroom E', 'Nancy Riess \xa0', 'Subject 5', 'Lecture'],
             [27, 'Classroom C', 'Nancy Riess \xa0', 'Subject 21', 'Lecture'],
             [40, 'Classroom E', 'Nancy Riess \xa0', 'Subject 19', 'Lecture'],
             [38, 'Classroom A', 'Waltraud Fill \xa0', 'Subject 24', 'Lecture'],
             [24, 'Classroom G', 'Nancy Riess \xa0', 'Subject 13', 'Lecture'],
             [38, 'Classroom C', 'Joi Shriver \xa0', 'Subject 23', 'Lecture'],
             [45, 'Classroom B', 'Nisha Pal \xa0', 'Subject 1', 'Lecture'],
             [47, 'Classroom H', 'Nancy Riess \xa0', 'Subject 19', 'Lecture'],
             [15, 'Classroom D', 'Tiffani Iannotti \xa0', 'Subject 24', 'Lecture'],
             [25, 'Classroom A', 'Ian Hooper \xa0', 'Subject 2', 'Lecture'],
             [21, 'Classroom E', 'Hobert Pascarella \xa0', 'Subject 12', 'Lecture'],
             [21, 'Classroom K', 'Lavenia Abdalla \xa0', 'Subject 15', 'Lecture'],
             [33, 'Classroom H', 'Lavenia Abdalla \xa0', 'Subject 13', 'Lecture'],
             [6, 'Classroom K', 'Ruth Frew \xa0', 'Subject 21', 'Lecture'],
             [48, 'Classroom E', 'Irina Foose \xa0', 'Subject 26', 'Lecture'],
             [61, 'Classroom A', 'Katherina Boutwell \xa0', 'Subject 20', 'Lecture'],
             [44, 'Lab F', 'Tyesha Gong \xa0', 'Subject 10-Lab', 'Lab'],
             [54, 'Classroom H', 'Katherina Boutwell \xa0', 'Subject 17', 'Lecture'],
             [50, 'Classroom K', 'Paul Vandergrift \xa0', 'Subject 18', 'Lecture'],
             [48, 'Classroom A', 'Tiffani Iannotti \xa0', 'Subject 15', 'Lecture'],
             [53, 'Classroom K', 'Freddie Seabrook \xa0', 'Subject 7', 'Lecture'],
             [4, 'Classroom A', 'Jane Courtney ', 'Subject 2', 'Lecture'],
             [53, 'Classroom J', 'Irina Foose \xa0', 'Subject 25', 'Lecture'],
             [39, 'Classroom K', 'Hobert Pascarella \xa0', 'Subject 23', 'Lecture'],
             [41, 'Classroom B', 'Lavenia Abdalla \xa0', 'Subject 19', 'Lecture'],
             [13, 'Classroom A', 'Tiffani Iannotti \xa0', 'Subject 13', 'Lecture'],
             [49, 'Classroom B', 'Paul Vandergrift \xa0', 'Subject 31', 'Lecture'],
             [18, 'Time', 'Joi Shriver \xa0', 'Subject 32-Lab', 'Lab'],
             [49, 'Classroom D', 'Paul Vandergrift \xa0', 'Subject 31', 'Lecture'],
             [14, 'Classroom I', 'Nisha Pal \xa0', 'Subject 11', 'Lecture'],
             [25, 'Classroom K', 'Ruth Frew \xa0', 'Subject 30', 'Lecture'],
             [51, 'Classroom H', 'Irina Foose \xa0', 'Subject 15', 'Lecture'],
             [30, 'Classroom C', 'Irina Foose \xa0', 'Subject 10', 'Lecture'],
             [2, 'Classroom K', 'Waltraud Fill \xa0', 'Subject 10', 'Lecture'],
             [14, 'Classroom G', 'Tyesha Gong \xa0', 'Subject 20', 'Lecture'],
             [62, 'Classroom H', 'Waltraud Fill \xa0', 'Subject 29', 'Lecture'],
             [40, 'Time', 'Jane Courtney ', 'Subject 2-Lab', 'Lab'],
             [6, 'Classroom E', 'Ian Hooper \xa0', 'Subject 2', 'Lecture'],
             [27, 'Classroom A', 'Lavenia Abdalla \xa0', 'Subject 14', 'Lecture'],
             [10, 'Classroom K', 'Nisha Pal \xa0', 'Subject 19', 'Lecture'],
             [57, 'Classroom F', 'Kristle Benshoof \xa0', 'Subject 23', 'Lecture'],
             [40, 'Classroom F', 'Katherina Boutwell \xa0', 'Subject 14', 'Lecture'],
             [3, 'Classroom A', 'Hobert Pascarella \xa0', 'Subject 22', 'Lecture'],
             [23, 'Classroom H', 'Nisha Pal \xa0', 'Subject 25', 'Lecture'],
             [34, 'Classroom K', 'Nam Mckeller \xa0', 'Subject 33', 'Lecture'],
             [37, 'Classroom I', 'Paul Vandergrift \xa0', 'Subject 10', 'Lecture'],
             [57, 'Classroom D', 'Joi Shriver \xa0', 'Subject 27', 'Lecture'],
             [46, 'Classroom A', 'Irina Foose \xa0', 'Subject 10', 'Lecture'],
             [62, 'Classroom I', 'Cathryn Bendel \xa0', 'Subject 28', 'Lecture'],
             [10, 'Lab E', 'Paul Vandergrift \xa0', 'Subject 17-Lab', 'Lab'],
             [41, 'Lab A', 'Paul Vandergrift \xa0', 'Subject 21-Lab', 'Lab'],
             [3, 'Classroom K', 'Paul Vandergrift \xa0', 'Subject 6', 'Lecture'],
             [27, 'Classroom K', 'Tyesha Gong \xa0', 'Subject 32', 'Lecture'],
             [63, 'Classroom K', 'Ruth Frew \xa0', 'Subject 13', 'Lecture'],
             [12, 'Classroom B', 'Tiffani Iannotti \xa0', 'Subject 5', 'Lecture'],
             [57, 'Classroom K', 'Nam Mckeller \xa0', 'Subject 33', 'Lecture'],
             [21, 'Classroom J', 'Joi Shriver \xa0', 'Subject 24', 'Lecture'],
             [62, 'Classroom J', 'Cathryn Bendel \xa0', 'Subject 10', 'Lecture'],
             [1, 'Classroom A', 'Tiffani Iannotti \xa0', 'Subject 9', 'Lecture'],
             [36, 'Classroom E', 'Eliza Biddle \xa0', 'Subject 15', 'Lecture'],
             [42, 'Classroom E', 'Eliza Biddle \xa0', 'Subject 16', 'Lecture'],
             [49, 'Classroom H', 'Waltraud Fill \xa0', 'Subject 23', 'Lecture'],
             [13, 'Classroom E', 'Ruth Frew \xa0', 'Subject 34', 'Lecture'],
             [28, 'Classroom B', 'Tyesha Gong \xa0', 'Subject 6', 'Lecture'],
             [31, 'Classroom G', 'Cathryn Bendel \xa0', 'Subject 25', 'Lecture'],
             [17, 'Classroom F', 'Hobert Pascarella \xa0', 'Subject 9', 'Lecture'],
             [38, 'Classroom D', 'Irina Foose \xa0', 'Subject 26', 'Lecture'],
             [24, 'Classroom B', 'Nam Mckeller \xa0', 'Subject 18', 'Lecture']]
from collections import Counter
from random import choice

rooms = ['Classroom A', 'Classroom B', 'Classroom C', 'Classroom D', 'Classroom E', 'Classroom F', 'Classroom G',
         'Classroom H', 'Classroom I', 'Classroom J', 'Classroom K']
lecturers = ['Jane Courtney ', 'Nam Mckeller \xa0', 'Kristle Benshoof \xa0', 'Freddie Seabrook \xa0',
             'Katherina Boutwell \xa0', 'Irina Foose \xa0', 'Nancy Riess \xa0', 'Tyesha Gong \xa0',
             'Cathryn Bendel \xa0', 'Paul Vandergrift \xa0', 'Nisha Pal \xa0', 'Ian Hooper \xa0',
             'Lavenia Abdalla \xa0', 'Tiffani Iannotti \xa0', 'Hobert Pascarella \xa0', 'Kylee Giblin \xa0',
             'Eliza Biddle \xa0', 'Waltraud Fill \xa0', 'Joi Shriver \xa0', 'Ruth Frew \xa0']

mutation_prob = 0.03


def calc_fitness(lst, index1, index2, index3):
    fitness = len(lst)  # When parsing through list, items count themselves in fitness,
    # to combat this, set fitness to the length of the list.
    ls = []
    for items in lst:
        for pieces in lst:
            if [items[index1], items[index2]] == [pieces[index1], pieces[index2]]:
                ls.append(lst.index(items))
                fitness -= 1
            elif [items[index1], items[index3]] == [pieces[index1], pieces[index3]]:
                lst.index(items)
                ls.append(lst.index(items))
                fitness -= 1
    counts = Counter(ls)
    ls = [id for id in ls if counts[id] > 1]
    ls = list(dict.fromkeys(ls))
    return fitness // 2, ls


def mutate(chromosome, ls, mutation_prob):
    original_fit = calc_fitness(chromosome, 0, 1, 2)[0]
    new_fit = original_fit
    while original_fit >= new_fit:
        for index in ls:
            randomTimeSlot = random.randint(0, 64)
            chromosome[index][0] = randomTimeSlot
            new_fit = calc_fitness(chromosome, 0, 1, 2)[0]
            if original_fit >= new_fit:
                randomRoom = choice(rooms)
                chromosome[index][1] = randomRoom
                new_fit = calc_fitness(chromosome, 0, 1, 2)[0]
                if original_fit >= new_fit:
                    lecturer = choice(lecturers)
                    chromosome[index][2] = lecturer
                    continue
    print(new_fit)
    if new_fit < -10:
        mutate(chromosome, ls, mutation_prob)
    else:
        return chromosome


fitness, ls = calc_fitness(timetable, 0, 1, 2)
chromosome = timetable
new = mutate(chromosome, ls, mutation_prob)
print(new)
